server:
  port: 8081
  servlet:
    context-path: /quartzStudy
spring:
  application:
    name: quartzStudy
  datasource:
    url: jdbc:mysql://localhost:3306/idle?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations:  classpath:mybatis/mapper/*.xml
  config-location:  classpath:mybatis/mybatis-config.xml